services:
  - type: web
    name: pyrogram-session-extractor
    runtime: python
    repo: https://github.com/kingali371/pyrogram-session-extractor
    plan: free
    envVars:
      - key: API_HASH
        sync: false
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
